import "/styles/reset.scss"
import "/styles/main.scss"
import "/styles/colors-and-types.scss"
import "/components/logo/logo.scss"
import "/components/header/header.scss"
import "/components/colors-and-types/color-block/color-block.scss"
import "/components/colors-and-types/type-block/type-block.scss"
