import "/index.pug"
import "/styles/main.scss"
import "/components/logo/logo.scss"
import "/components/header/header.scss"
import "/components/color-block/color-block.scss"
import "/components/type-block/type-block.scss"
import "/components/colors-and-types/colors-and-types.scss"
